apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dox-runner-set
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.12.0
    helm:
      releaseName: dox-runner-set
      values: |
        githubConfigUrl: https://github.com/dox-cli-demo
        githubConfigSecret: dox-runner-secret
        runnerGroup: Default
        minRunners: 1
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-gha-rs-controller
        template:
          spec:
            initContainers:
              - name: fix-perms
                image: alpine/git
                command: ["sh", "-c"]
                args:
                  - |
                    echo "Cloning dox-devops-base repo..." && git clone --depth=1 https://github.com/dox-cli-demo/dox-devops-base.git /home/runner/dox_customize && \
                    echo "Setting ownership..." && \
                    chown -R 1001:1001 /home/runner/dox_resources && \
                    chown -R 1001:1001 /home/runner/dox_customize
                volumeMounts:
                  - name: dox-resources
                    mountPath: /home/runner/dox_resources
                  - name: dox-customize
                    mountPath: /home/runner/dox_customize

            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:2.325.0
                command: ["/bin/bash", "-c"]
                args:
                  - curl -s -L -o install.sh https://github.com/dopxlab/dox-cli/releases/latest/download/install.sh  && bash install.sh && /home/runner/run.sh
                envFrom:
                  - secretRef:
                      name: dox-runner-secret
                env:
                  - name: DOX_RESOURCES_DIR
                    value: /home/runner/dox_resources
                  - name: DOX_USER_BIN
                    value: /home/runner/.dox/bin
                  - name: DOX_CUSTOM_DIR
                    value: /home/runner/dox_customize
                  - name: PATH
                    value: /home/runner/.dox/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                  - name: DOCKER_BUILDKIT
                    value: "1"
                  - name: BUILDKIT_HOST
                    value: tcp://127.0.0.1:1234
                volumeMounts:
                  - name: dox-customize
                    mountPath: /home/runner/dox_customize
                  - name: dox-resources
                    mountPath: /home/runner/dox_resources
                    subPath: resources
                  - name: dox-resources
                    mountPath: /home/runner/.m2
                    subPath: m2
                  - name: dox-resources
                    mountPath: /home/runner/.trivy
                    subPath: trivy  
                  - name: dox-resources
                    mountPath: /home/runner/.cache
                    subPath: cache
                  - name: dox-resources
                    mountPath: /var/lib/buildkit

              - name: buildkitd
                image: moby/buildkit:latest
                args: ["--addr", "tcp://0.0.0.0:1234"]
                ports:
                  - containerPort: 1234
                volumeMounts:
                  - name: dox-resources
                    mountPath: /var/lib/buildkit

            volumes:
              - name: dox-customize
                emptyDir: {}
              - name: dox-resources
                persistentVolumeClaim:
                  claimName: dox-resources-pvc

  destination:
    server: https://kubernetes.default.svc
    namespace: dox-runners
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
