---
apiVersion: v1
kind: Namespace
metadata:
  name: dox-nfs
---
apiVersion: v1
kind: Namespace
metadata:
  name: dox-runners
---
# Storage Class (same as before)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dox-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
# Static Persistent Volume (acts like NFS)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dox-static-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: dox-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/dox-resources
