# Install RWX for Ranger
# helm repo add longhorn https://charts.longhorn.io
# helm repo update
# helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dox-resources-pvc
  namespace: dox-runners
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
