apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dox-resources-pvc
  namespace: dox-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
